"""Alembic environment.

The database URL comes from the environment, never from alembic.ini, so the
same migration set runs against a developer's throwaway container and against
production without editing a file that is checked in.

There is no target_metadata and no autogenerate: the schema is written by hand
in the revision files. This project has one small, deliberate schema, and a
hand-written migration says what it means to do, which an autogenerated diff
does not.
"""

from __future__ import annotations

import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)


def database_url() -> str:
    """The URL to migrate, normalised for SQLAlchemy.

    The service itself talks to psycopg directly and wants a plain
    ``postgresql://`` URL. SQLAlchemy reads that as a request for psycopg2,
    which is not installed and is not wanted, so the driver is pinned here
    rather than making every caller write ``postgresql+psycopg://`` in an
    environment variable that psycopg would then reject.
    """
    url = os.environ.get("SMTSIM_DATABASE_URL") or os.environ.get("SMTSIM_TEST_DATABASE_URL")
    if not url:
        raise RuntimeError(
            "SMTSIM_DATABASE_URL is not set. Migrations never guess at a database."
        )
    if url.startswith("postgresql://"):
        return url.replace("postgresql://", "postgresql+psycopg://", 1)
    if url.startswith("postgres://"):
        return url.replace("postgres://", "postgresql+psycopg://", 1)
    return url


def run_migrations_offline() -> None:
    context.configure(
        url=database_url(),
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    section = config.get_section(config.config_ini_section, {})
    section["sqlalchemy.url"] = database_url()
    connectable = engine_from_config(section, prefix="sqlalchemy.", poolclass=pool.NullPool)

    with connectable.connect() as connection:
        context.configure(connection=connection)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
